common:
  env: dev
  deploy_dir: /home/dev/deploy # 部署目录,存放log等
  log_level: info

server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60

mysql:
  host: 38.181.56.40
  port: 3306
  user: root
  password: ms@123#
  database: Prod

redis:
  url: redis://localhost:6379/0
