CREATE TABLE `users` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  sol_address VARCHAR(128) NOT NULL COMMENT 'sol钱包地址',
  username VARCHAR(64) DEFAULT NULL COMMENT '昵称，可选',
  points DECIMAL(18, 6) NOT NULL DEFAULT 0 COMMENT '积分',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  UNIQUE KEY idx_sol_address (`sol_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';


CREATE TABLE `event` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
  event_type ENUM('TASK_COMPLETE', 'ON_CHAIN_TRANSFER') NOT NULL COMMENT '事件类型',
  metadata JSON DEFAULT NULL COMMENT '事件具体数据',
  event_time DATETIME NOT NULL COMMENT '事件发生时间',
  created_by BIGINT UNSIGNED NOT NULL COMMENT '创建人ID',
  updated_by BIGINT UNSIGNED NOT NULL COMMENT '更新人ID', 
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  KEY idx_user_id (`user_id`),
  KEY idx_event_type (`event_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件表';
