CREATE TABLE `users` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  sol_address VARCHAR(128) NOT NULL COMMENT 'sol钱包地址',
  username VARCHAR(64) DEFAULT NULL COMMENT '昵称，可选',

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  UNIQUE KEY idx_sol_address (`sol_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';


CREATE TABLE `event` (
  id VARCHAR(64) NOT NULL COMMENT '事件ID，如 TASK_COMPLETE、ON_CHAIN_TRANSFER 等',
  name VARCHAR(128) NOT NULL COMMENT '事件名称',
  description TEXT COMMENT '事件描述',

  created_by VARCHAR(64) NOT NULL COMMENT '创建人ID',
  updated_by VARCHAR(64) NOT NULL COMMENT '更新人ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件表';

CREATE TABLE `event_point_rule` (
  `id` VARCHAR(64) NOT NULL COMMENT '规则ID，唯一',
  `event_id` VARCHAR(64) NOT NULL COMMENT '关联事件ID',
  `points` DECIMAL(18,6) NOT NULL COMMENT '触发该事件时奖励的积分数量，支持正负',
  `description` VARCHAR(256) DEFAULT NULL COMMENT '规则描述',

  -- 公共字段
  `created_by` VARCHAR(64) NOT NULL COMMENT '创建人ID',
  `updated_by` VARCHAR(64) NOT NULL COMMENT '更新人ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_event_rule` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件对应积分奖励规则表';


CREATE TABLE `event_record` (
  id VARCHAR(64) NOT NULL COMMENT '事件记录ID，唯一',
  event_id VARCHAR(64) NOT NULL COMMENT '事件ID',
  user_id VARCHAR(64) NOT NULL COMMENT '触发事件的用户ID',
  metadata JSON DEFAULT NULL COMMENT '事件具体数据，比如任务详情、链上tx哈希等',
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '事件发生时间',

  created_by VARCHAR(64) NOT NULL COMMENT '创建人ID',
  updated_by VARCHAR(64) NOT NULL COMMENT '更新人ID',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  KEY idx_event_id (`event_id`),
  KEY idx_user_id (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='事件记录表';