CREATE TABLE `users` (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  sol_address VARCHAR(128) NOT NULL COMMENT 'sol钱包地址',
  username VARCHAR(64) DEFAULT NULL COMMENT '昵称，可选',

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  is_deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否删除（0否，1是）',

  PRIMARY KEY (`id`),
  UNIQUE KEY idx_sol_address (`sol_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';